name: Trying for different shell

on:
   push:
      branches: [ main ]
      
jobs:
   run_windows_command:
      runs-on: windows-latest
      steps:
         - name: powershell command
           run: Get-Location
           shell: powershell
           
   run_command:
      runs-on: ubuntu-latest
      steps:
         - name: linux command
           run: pwd
         - name: python command
           run: |
              import platform
              print(platform.processor())
           
   
