name: Trying for different shell

on:
   push:
      branches: [ main ]
      
jobs:
   run_windows_command:
      runs-on: windows-latest
      steps:
         - name: powershell command
           run: Get-Location
           shell: powershell
           
   run_linux_command:
      runs-on: ubuntu-latest
      steps:
         - name: linux command
           run: pwd
   
